# Main build pipeline that verifies, builds, and deploys the software
name: Build Docker image (ghcr.io)
# Events that trigger the workflow
on:
  # Run workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Application version to build container image for
        required: true

# Only allow 1 execution of this workflow to be running at any given time per-branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables
env:
  LF_INPUT_IMAGE_NAME: "swot-confluence/lakeflow_input"
  LF_DEPLOY_IMAGE_NAME: "swot-confluence/lakeflow_deploy"
  REGISTRY: ghcr.io

jobs:
  container:
    name: Build container image
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ github.event.inputs.version }}
    steps:
      # Check out GitHub repo
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}

      # ghcr.io container image
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker FLPE
        id: meta-lf-input
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.LF_INPUT_IMAGE_NAME }}
          tags: |
            type=pep440,pattern={{version}},value=${{ env.APP_VERSION }}
          flavor: |
            latest=true

      - name: Build and push Docker image INPUT
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_input
          push: true
          pull: true
          tags: ${{ steps.meta-lf-input.outputs.tags }}
          labels: ${{ steps.meta-lf-input.outputs.labels }}

      - name: Extract metadata (tags, labels) for Docker DEPLOY
        id: meta-lf-deploy
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.LF_DEPLOY_IMAGE_NAME }}
          tags: |
            type=pep440,pattern={{version}},value=${{ env.APP_VERSION }}
          flavor: |
            latest=true

      - name: Build and push Docker image DEPLOY
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_deploy
          push: true
          pull: true
          tags: ${{ steps.meta-lf-deploy.outputs.tags }}
          labels: ${{ steps.meta-lf-deploy.outputs.labels }}